### ISSUE TITLE
[BUG] Right click menu not working when scene rotated 90

### ISSUE THREAD

**Issue by Muttles** [MaterialFoundry/LockView#103]
Any right click menu is disabled when scene image is rotated.

**Comment by CDeenen** [comment]
@Dylancyclone since you implemented the scene rotation, is this something you'd be willing to look into?
This has been mentioned by multiple people and if there's no fix for it I'm not sure if I want to keep the scene rotation in the module.

What I've found is that when the scene is rotated the right click menu is displayed in a completely wrong location, see the attached image. Maybe it's trying to display it on the spot where the token would be if the scene wasn't rotated.
![image](https://github.com/CDeenen/LockView/assets/68693756/68fc0263-a85e-46bb-b74c-e72e78df1e1d)

**Comment by Dylancyclone** [comment]
Hi, sure I can take a look. I'm currently out of town, but I will investigate once I get back

**Comment by Dylancyclone** [comment]
Hi, I created a pull request to fix this. Let me know what you think! https://github.com/MaterialFoundry/LockView/pull/106
